### ISSUE TITLE
可以加入网易云日推歌单自动同步到spotify吗

### ISSUE THREAD

**Issue by yitong2333** [muyangye/Netease_To_Spotify#1]

**Comment by muyangye** [comment]
哈喽这个feature request的意思是用网易云的日推替换spotify的日推还是每天网易云的日推都在spotify创建一个歌单呢？应该可以做

**Comment by yitong2333** [comment]
> 

每天网易云的日推都在spotify创建一个歌单

**Comment by muyangye** [comment]
最近刚入职比较忙，刚刚看了一下这个好像做不了，因为pyncm这个库没有日推api，网易云的api是只开放给合作方的，除非找到Python另外有日推的网易云api库或者自己破解网易云api(?)不然暂时做不了==

**Comment by yitong2333** [comment]
> [刚看了下GitHub上有另一个类似的项目，但是不便于使用，兄弟可以参考以下owo
[链接](https://github.com/GalvinGao/NeteaseRecommendationSync)
