### ISSUE TITLE
博主求助！

### ISSUE THREAD

**Issue by khazic** [muyangye/Netease_To_Spotify#2]
能详细说一下config里面的那几个参数是什么吗？除了最后一个网易云的id 其他几个我都拿不准

**Comment by khazic** [comment]
(khazic) khazics-MacBook-Pro:Netease_To_Spotify-main liuyibo$ python cli.py 
---------- Starting to Migrate ----------
Response is not valid JSON : Extra data: line 1 column 26 (char 25)
Response : <Response [200]>
Traceback (most recent call last):
  File "/Users/liuyibo/Desktop/Netease_To_Spotify-main/cli.py", line 8, in <module>
    main()
  File "/Users/liuyibo/Desktop/Netease_To_Spotify-main/cli.py", line 5, in main
    app.migrate()
  File "/Users/liuyibo/Desktop/Netease_To_Spotify-main/netease_to_spotify.py", line 39, in migrate
    for name, artist in self.get_netease_playlist_tracks_name_and_artist():
  File "/Users/liuyibo/Desktop/Netease_To_Spotify-main/netease_to_spotify.py", line 118, in get_netease_playlist_tracks_name_and_artist
    songs = apis.track.GetTrackDetail(track_ids)["songs"]
TypeError: 'Response' object is not subscriptable
(khazic) khazics-MacBook-Pro:Netease_To_Spotify-main liuyibo$

**Comment by khazic** [comment]
redirect_uri : "http://localhost:3000"
  spotify_playlist_name : "easymoneysniper1"
  cover_image_path : "/Users/liuyibo/Desktop/Netease_To_Spotify-main/netease.png"
  netease_playlist_id : "7633481963"
  
  
  client那个 我应该是填对了的 但是还是报的错误

**Comment by muyangye** [comment]
哈喽，我刚刚试了下，是pyncm API的问题，"7633481963"这个歌单>1000首歌太长了所以[pyncm不支持](https://github.com/mos9527/pyncm/blob/master/pyncm/apis/track.py#L16)，我刚刚换了几个更短的歌单是没问题的。这个因为是第三方库的问题暂时没法解决，我去把这个限制补在readme里，多谢提这个issue哈哈

**Comment by khazic** [comment]
哦哦哦那我删点歌曲再试试效果哈 感谢指导 祝你生活愉快

**Comment by muyangye** [comment]
其实我可以改改我的逻辑把>1000首歌拆成几份1000首之内的，不过我在美西两点了要写完测试完可能不太够时间，你如果马上就要用的话没什么办法😢但是明天我去把这个写了

**Comment by khazic** [comment]
好的 感谢博主 明天我再来测试您的代码

**Comment by muyangye** [comment]
改好了哦，记得重新装一下requirements，多了个进度条歌单太长的话方便看进度 :-)

**Comment by khazic** [comment]
哇 好的哥 你这效率真快

**Comment by khazic** [comment]
我已经成功导入歌单 感谢 可以关闭该issue了
